[tool.black]
line-length = 120
target-version = ['py38']

# regex
exclude = '''
/(
  \.git
  | \.?venv
  | \.mypy_cache
  | br-*
  | branch-*
  | data
  | libs
  | stubs
  | tests/files
  | typings
)/
'''

[tool.pyright]
include = ['./']
exclude = [
  '**/__pycache__/',
  '**/node_modules/',
  # git-related
  '**/.git/',
  '**/br-*/',
  '**/branch-*/',
]
ignore = [
  '**/.venv',
  '**/libs',
]
stubPath = 'typings'
pythonVersion = '3.8'
